{The following Strings must be translated too:}

{GPF Messages}
'MOD4WIN se pokusil provest neco hrozneho se systemem a byl ukoncen!'+#10+
'Udelali jsme vse pro hladky konec, ale nektere prostredky asi zustanou'+#10+
'v pameti a system se muze stat nestabilnim!'

'Pokusili jsme se delit nulou v modulu %s na adrese [%04X:%04X]!'
'Pokusili jsme se vykonat neplatnou operaci v modulu %s na adrese [%04X:%04X]!'
'Zpusobili jsme preteceni zasobniku v modulu %s na adrese [%04X:%04X]!'
'Pristupovali jsme do pameti, ktera nam nepatrila, v modulu %s na adrese [%04X:%04X]!'
'Zpusobili jsme neplatnost stranky pameti v modulu %s na adrese [%04X:%04X]!'

{INSTALLATION}
'Vitejte'
'v programu'
'MOD4WIN 2.40'
'Kliknete'
'na tlacitko s'
'vasim jazykem'

{Install.INF}
'Ukázkové moduly     :'
'Anglická nápovìda   :'
'Nìmecká nápovìda    :'
'Francouzská nápovìda:'
'Španìlská nápovìda  :'
'Øecká nápovìda      :'
'Èeská nápovìda      :'