{The following Strings must be translated too:}

{GPF Messages}
'MOD4WIN tried to do something awful with your system and was closed!'+#10+
'We did our best for a safe termination but some resources will probably'+#10+
'remain static in your memory and your system could get unstable!'

'We tried to divide something by zero in module %s at address [%04X:%04X]!'
'We tried to execute an invalid opcode in module %s at address [%04X:%04X]!'
'We caused a memory stack overflow in module %s at address [%04X:%04X]!'
'We accessed memory we didn''t actually own in module %s at address [%04X:%04X]!'
'We caused a memory page fault in module %s at address [%04X:%04X]!'

{INSTALLATION}
'Welcome'
'to'
'MOD4WIN 2.30'
'Click the'
'button with'
'your language'

{Install.INF}
'Sample Modules  :'
'English Help    :'
'German Help     :'
'French Help     :'
'Spanish Help    :'
'Greek Help      :'
