{The following Strings must be translated too:}

{GPF Messages}
'MOD4WIN ha compromesso l' integrità del sistema ed è stato chiuso!'+#10+
'E' stato tentato tutto il possibile per una terminazione sicura ma probabilmente alcune risorse'+#10+
'rimangono statiche in memoria e il sistema potrebbe diventare instabile!'

'Si è tentata una divisione per zero nel modulo %s all' indirizzo [%04X:%04X]!'
'Si è tentata una esecuzione invalida di opcode nel modulo %s all' indirizzo [%04X:%04X]!'
'Si è causato un overflow di memoria nel modulo %s all' indirizzo [%04X:%04X]!'
'Si è tentato di accedere a memoria non disponibile nel modulo %s  all' indirizzo [%04X:%04X]!'
'Si è causato un errore nella pagina di memoria nel modulo %s all' indirizzo [%04X:%04X]!'

{INSTALLATION}
'Benvenuti'
'in'
'MOD4WIN 2.30'
'Premete il'
'pulsante con'
'la vostra lingua'

{Install.INF}
'Moduli di esempio :'
'Guida inglese     :'
'Guida tedesca     :'
'Guida francese    :'
'Guida spagnola    :'
'Guida greca       :'
'Guida italiana    :'
