{The following Strings must be translated too:}

{GPF Messages}
'MOD4WIN probeerde iets raars met uw systeem te doen en is afgesloten!'+#10+
'We hebben ons best gedaan om alles veilig af te sluiten, maar sommige'+#10+
'resources kunnen achterblijven in het geheugen en uw systeem instabiel'+#10+
'maken. U doet er goed aan uw systeem opnieuw te starten!'+#10+

'We probeerden iets door nul te delen in module %s op adres [%04X:%04X]!'
'We probeerden een ongeldige opcode uit te voeren in module %s op adres [%04X:%04X]!'
'We veroorzaakten een geheugen stack overflow in module %s op adres [%04X:%04X]!'
'We gebruikten geheugen wat eigenlijk niet toegankelijk was in module %s op adres [%04X:%04X]!'
'We veroorzaakten en geheugen pagina fout in module %s op adres [%04X:%04X]!'

{INSTALLATION}
'Welkom'
'bij'
'MOD4WIN 2.30'
'Klik de'
'knop met'
'jouw taal'

{Install.INF}
'Voorbeeld Modules  :'
'Engelse Help    :'
'Duitse Help     :'
'Franse Help     :'
'Spaanse Help    :'
'Griekse Help      :'
'Nederlandse Help      :'