{The following Strings must be translated too:}

{GPF Messages}
'¡MOD4WIN intentó hacer alguna maldad a su sistema y fue cerrado!'+#10+
'Hemos hecho lo posible para que la salida del programa sea segura, pero algunos recursos pueden'+#10+
'haberse quedado en su memoria y su sistema puede volverse inestable'

'Hemos intentado dividir algo por cero en el módulo %s dirección [%04X:%04X]!'
'Hemos intentado ejecutar un opcode inválido en el modulo %s dirección [%04X:%04X]!'
'Hemos causado un desbordamiento de la pila en el mádulo %s dirección [%04X:%04X]!'
'Hemos accedido a memoria que no nos pertenece en el módulo %s dirección [%04X:%04X]!'
'Hemos causado un fallo de paginación de memoria en el módulo %s dirección [%04X:%04X]!'

{INSTALLATION}
'Bienvenido'
'a'
'MOD4WIN 2.40'
'Pulse el'
'botón de'
'su idioma'

{Install.INF}
'Módulos de ejemplo:'
'Ayuda en Inglés   :'
'Ayuda en Alemán   :'
'Ayuda en Francés  :'
'Ayuda en Español  :'
'Ayuda en Griego   :'
